CREATE TABLE parcel
(
    id                               UUID         NOT NULL,
    delivery_method                  VARCHAR(255) NOT NULL,
    start_address                    VARCHAR(255) NOT NULL,
    destination_address              VARCHAR(255) NOT NULL,
    dimensions_id                    BIGINT       NOT NULL,
    current_parcel_machine_locker_id BIGINT,
    current_warehouse_id             BIGINT,
    start_parcel_machine_id          BIGINT       NOT NULL,
    destination_parcel_machine_id    BIGINT       NOT NULL,

    CONSTRAINT pk_parcel PRIMARY KEY (id)
);

CREATE TABLE parcel_dimensions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size       VARCHAR(255)                            NOT NULL,
    max_length DOUBLE PRECISION                        NOT NULL,
    max_width  DOUBLE PRECISION                        NOT NULL,
    max_height DOUBLE PRECISION                        NOT NULL,
    unit       VARCHAR(255)                            NOT NULL,
    price      DOUBLE PRECISION                        NOT NULL,

    CONSTRAINT pk_parceldimensions PRIMARY KEY (id)
);

CREATE TABLE parcel_machine
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_parcelmachine PRIMARY KEY (id)
);

CREATE TABLE parcel_machine_locker
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    locker_id         VARCHAR(255)                            NOT NULL,
    parcel_machine_id BIGINT                                  NOT NULL,
    stored_parcel_id  UUID,

    CONSTRAINT pk_parcelmachinelocker PRIMARY KEY (id)
);

CREATE TABLE parcel_status_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_status_group VARCHAR(255)                            NOT NULL,
    delivery_status       VARCHAR(255)                            NOT NULL,
    address               VARCHAR(255)                            NOT NULL,
    parcel_id             UUID                                    NOT NULL,

    CONSTRAINT pk_parcelstatushistory PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id    VARCHAR(255)                            NOT NULL,
    amount        DECIMAL(10, 2)                          NOT NULL,
    currency_code VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    parcel_id     UUID                                    NOT NULL,

    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE warehouse
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

ALTER TABLE parcel_machine_locker
    ADD CONSTRAINT uc_parcelmachinelocker_stored_parcel UNIQUE (stored_parcel_id);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_parcel UNIQUE (parcel_id);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_paymentid UNIQUE (payment_id);

ALTER TABLE parcel_machine_locker
    ADD CONSTRAINT FK_PARCELMACHINELOCKER_ON_PARCELMACHINE FOREIGN KEY (parcel_machine_id) REFERENCES parcel_machine (id);

ALTER TABLE parcel_machine_locker
    ADD CONSTRAINT FK_PARCELMACHINELOCKER_ON_STORED_PARCEL FOREIGN KEY (stored_parcel_id) REFERENCES parcel (id);

ALTER TABLE parcel_status_history
    ADD CONSTRAINT FK_PARCELSTATUSHISTORY_ON_PARCEL FOREIGN KEY (parcel_id) REFERENCES parcel (id);

ALTER TABLE parcel
    ADD CONSTRAINT FK_PARCEL_ON_CURRENTPARCELMACHINELOCKER FOREIGN KEY (current_parcel_machine_locker_id) REFERENCES parcel_machine_locker (id);

ALTER TABLE parcel
    ADD CONSTRAINT FK_PARCEL_ON_CURRENTWAREHOUSE FOREIGN KEY (current_warehouse_id) REFERENCES warehouse (id);

ALTER TABLE parcel
    ADD CONSTRAINT FK_PARCEL_ON_DESTINATIONPARCELMACHINE FOREIGN KEY (destination_parcel_machine_id) REFERENCES parcel_machine (id);

ALTER TABLE parcel
    ADD CONSTRAINT FK_PARCEL_ON_DIMENSIONS FOREIGN KEY (dimensions_id) REFERENCES parcel_dimensions (id);

ALTER TABLE parcel
    ADD CONSTRAINT FK_PARCEL_ON_STARTPARCELMACHINE FOREIGN KEY (start_parcel_machine_id) REFERENCES parcel_machine (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_PARCEL FOREIGN KEY (parcel_id) REFERENCES parcel (id);
