CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE delivery
(
    id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parcel_id                            UUID,
    delivery_method                      VARCHAR(255),
    status                               VARCHAR(255),
    start_address                        VARCHAR(255),
    destination_address                  VARCHAR(255),
    start_parcel_machine_locker_id       BIGINT,
    destination_parcel_machine_locker_id BIGINT,
    start_warehouse_id                   BIGINT,
    destination_warehouse_id             BIGINT,
    CONSTRAINT pk_delivery PRIMARY KEY (id)
);

CREATE TABLE delivery_record
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_status VARCHAR(255)                            NOT NULL,
    delivery_id     BIGINT,
    parcel_id       UUID,
    CONSTRAINT pk_deliveryrecord PRIMARY KEY (id)
);

ALTER TABLE parcel_machine
    ADD available_lockers_count INTEGER;

ALTER TABLE parcel_machine
    ALTER COLUMN available_lockers_count SET NOT NULL;

ALTER TABLE parcel_machine
    ADD lockers_count INTEGER;

ALTER TABLE parcel_machine
    ALTER COLUMN lockers_count SET NOT NULL;

ALTER TABLE delivery_record
    ADD CONSTRAINT FK_DELIVERYRECORD_ON_DELIVERY FOREIGN KEY (delivery_id) REFERENCES delivery (id);

ALTER TABLE delivery_record
    ADD CONSTRAINT FK_DELIVERYRECORD_ON_PARCEL FOREIGN KEY (parcel_id) REFERENCES parcel (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_DESTINATION_PARCEL_MACHINE_LOCKER FOREIGN KEY (destination_parcel_machine_locker_id) REFERENCES parcel_machine_locker (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_DESTINATION_WAREHOUSE FOREIGN KEY (destination_warehouse_id) REFERENCES warehouse (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_PARCEL FOREIGN KEY (parcel_id) REFERENCES parcel (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_START_PARCEL_MACHINE_LOCKER FOREIGN KEY (start_parcel_machine_locker_id) REFERENCES parcel_machine_locker (id);

ALTER TABLE delivery
    ADD CONSTRAINT FK_DELIVERY_ON_START_WAREHOUSE FOREIGN KEY (start_warehouse_id) REFERENCES warehouse (id);

ALTER TABLE parcel_status_history
    DROP CONSTRAINT fk_parcelstatushistory_on_parcel;

DROP TABLE parcel_status_history CASCADE;

ALTER TABLE parcel_dimensions
    DROP COLUMN unit;

ALTER TABLE payment
    DROP COLUMN amount;

ALTER TABLE payment
    ADD amount DECIMAL(10, 2) NOT NULL;

ALTER TABLE parcel
    ALTER COLUMN destination_address DROP NOT NULL;

ALTER TABLE parcel
    ALTER COLUMN destination_parcel_machine_id DROP NOT NULL;

ALTER TABLE parcel_machine_locker
    DROP COLUMN locker_id;

ALTER TABLE parcel_machine_locker
    ADD locker_id INTEGER NOT NULL;

ALTER TABLE parcel
    ALTER COLUMN start_address DROP NOT NULL;

ALTER TABLE parcel
    ALTER COLUMN start_parcel_machine_id DROP NOT NULL;